version: 2

# Set the version of Python and other tools you might need
# build:
#   os: ubuntu-22.04
#   tools:
#     python: "3.10"
#   jobs:
#     pre_build:
#       # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
#       - "jupyter-book config sphinx reports/"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: reports/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
  - epub

python:
version: 3.10
   install:
   - requirements: reports/requirements_jb.txt
#   - method: pip
#     path: .


