outpath: 'results' # folder path for all saved finetuned models
models:
    bert-base-cased.zip: '1RCbC2rCkckt7K1ZZ_hT6DTUFKubFk3_8' # file name for bert based finetuned model
    finbert.zip: '1UGx_rTooMhU5FamNc-CDhdZevIhMJBWr' #finbert finetuned model
    xlnet.zip: '1d2rUSBRcDDnyIXdrs6VpMhA6ZSMmywes' # xlnet fintuned model
    roberta.zip: '1Kl0nRTNGcEdJSB77ifPrOCc5Qzl6dPOn' # roberta finetuned model